import os
import re
from dotenv import load_dotenv
from langchain_huggingface.embeddings import HuggingFaceEmbeddings
from langchain_qdrant import QdrantVectorStore
from groq import Groq

# Load API Keys
load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
MODEL_ID = "openai/gpt-oss-120b" # upgraded model for complex medical generation
QDRANT_URL = os.getenv("QDRANT_URL","http://localhost:6366")
COLLECTION_NAME = "ICU_RAG"

# Embeddings
embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# Vector DB
vector_db = QdrantVectorStore.from_existing_collection(
    url=QDRANT_URL,
    api_key=os.getenv("QDRANT_API_KEY_CLOUD"),
    collection_name=COLLECTION_NAME,
    embedding=embedding_model,
)

# LLM Client
client = Groq(api_key=GROQ_API_KEY)


def clean_text(text):
    return re.sub(r"\s+", " ", text).strip()

def build_context(docs):
    seen = set()
    chunks = []

    for i, doc in enumerate(docs):
        content = clean_text(doc.page_content)
        if content not in seen:
            seen.add(content)
            source = doc.metadata.get("source", "Unknown")
            chunks.append(f"[Source: {source}]: {content}")

    return "\n\n".join(chunks)

def generate_search_queries(report: str):
    """Ask LLM to generate targeted medical guideline search queries based on the team's json report"""
    prompt = f"""
    Based on the following JSON clinical report, generate 3 specific search queries to find relevant clinical guidelines or medical protocols for the conditions/abnormalities found.
    Return only the queries separated by newlines, no extra text.
    
    Report:
    {report}
    """
    res = client.chat.completions.create(
        messages=[{"role": "user", "content": prompt}],
        model="llama-3.1-8b-instant",
        temperature=0.1,
        max_tokens=100
    )
    return res.choices[0].message.content.split('\n')

def medical_guideline_rag(patient_data: str, medical_team_report: str):
    print("DEBUG: Initiating medical guideline RAG...")
    
    # 1. Search Vector DB based on the medical report's findings
    queries = generate_search_queries(medical_team_report)
    all_docs = []
    
    for q in queries:
        if q.strip():
            docs = vector_db.max_marginal_relevance_search(q.strip(), k=2, fetch_k=10)
            all_docs.extend(docs)
            
    context = build_context(all_docs)

    # 2. Enrich the report with the fetched guidelines
    final_prompt = f"""
    You are an expert clinical validation and RAG augmentation system.
    
    You are provided with:
    1. Raw Patient Historical Data (labs/tests)
    2. A Structural Clinical Insights JSON Report generated by our AI agent team
    3. Retrieved Medical Guidelines/Protocols from trusted PDF sources
    
    YOUR TASK:
    Transform the clinical insights JSON into a beautifully readable, comprehensive Final Patient Report.
    Crucially, you MUST use the "Retrieved Medical Guidelines" to cite standard clinical protocols or guidelines relevant to the patient's abnormalities. 
    Only use the RAG guidelines to explain WHY an abnormality matters and WHAT the standard protocol says.
    
    CRITICAL RULES:
    - Base your RAG citations purely on the provided context. Use format: (Source: [Doc Name])
    - Keep the output professional, clinical, and reassuring.
    - Format nicely with markdown headings and bullet points.
    - At the bottom, include a strong, professional safety disclaimer.

    ==== RAW PATIENT DATA ====
    {patient_data}
    
    ==== CLINICAL INSIGHTS JSON REPORT (Agent Output) ====
    {medical_team_report}
    
    ==== RETRIEVED MEDICAL GUIDELINES (RAG Context) ====
    {context}
    """

    chat = client.chat.completions.create(
        messages=[
            {"role": "system", "content": "You are a top-tier medical RAG system validating and finalizing clinical reports."},
            {"role": "user", "content": final_prompt}
        ],
        model=MODEL_ID,
        max_tokens=2000,
        temperature=0.15
    )

    return chat.choices[0].message.content
